import { createFileRoute } from "@tanstack/react-router";
import { ArrowUpRight, Clock3, Instagram, MapPin, MessageCircle, Phone } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ADDRESS, DIRECTIONS, INSTAGRAM, PHONE, whatsappUrl } from "@/lib/jewellery";
import storePiece from "@/assets/jewellery-11.png.asset.json";

export const Route = createFileRoute("/visit")({ head: () => ({ meta: [
  { title: "Visit Us | Shivani Jewellers Meerut" },
  { name: "description", content: "Visit Shivani Jewellers on Mansa Devi Road, Jagriti Vihar, Meerut. Open Tuesday to Sunday, 10 AM to 8 PM. Call or message us." },
  { property: "og:title", content: "Visit Us | Shivani Jewellers Meerut" },
  { property: "og:description", content: "Find Shivani Jewellers in Jagriti Vihar, Meerut. Open Tuesday to Sunday, 10 AM to 8 PM." },
  { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: Visit });

function Visit() { return <main><section className="mx-auto grid max-w-[1440px] md:min-h-[650px] md:grid-cols-2"><div className="flex flex-col justify-center px-5 py-16 md:px-10 md:py-24 lg:px-16"><p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-accent">We'd love to see you</p><h1 className="mt-5 font-display text-6xl leading-[0.95] md:text-7xl">Visit <span className="italic">Shivani</span> Jewellers.</h1><p className="mt-7 max-w-md text-sm leading-8 text-muted-foreground">See the details up close, find your favourite piece, and let us help you choose something special.</p><div className="mt-10 space-y-7 border-t border-border pt-9"><div className="flex gap-4"><MapPin className="mt-1 shrink-0 text-accent" size={22} strokeWidth={1.4} /><div><h2 className="text-xs font-semibold uppercase tracking-[0.15em]">Our store</h2><p className="mt-2 max-w-sm text-sm leading-7 text-muted-foreground">{ADDRESS}</p></div></div><div className="flex gap-4"><Clock3 className="mt-1 shrink-0 text-accent" size={22} strokeWidth={1.4} /><div><h2 className="text-xs font-semibold uppercase tracking-[0.15em]">Opening hours</h2><p className="mt-2 text-sm leading-7 text-muted-foreground">Tuesday – Sunday · 10:00 AM – 8:00 PM<br />Monday · Closed</p></div></div><div className="flex gap-4"><Phone className="mt-1 shrink-0 text-accent" size={22} strokeWidth={1.4} /><div><h2 className="text-xs font-semibold uppercase tracking-[0.15em]">Call us</h2><a href={`tel:+91${PHONE}`} className="mt-2 block text-sm text-muted-foreground hover:text-accent">+91 {PHONE}</a></div></div></div><div className="mt-10 flex flex-wrap gap-3"><Button variant="luxury" size="tall" asChild><a href={DIRECTIONS} target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={16} /></a></Button><Button variant="luxuryOutline" size="tall" asChild><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer"><MessageCircle size={16} /> WhatsApp us</a></Button></div></div><div className="relative min-h-[440px] bg-secondary"><img src={storePiece.url} alt="Gold floral necklace and earrings at Shivani Jewellers" className="absolute inset-0 h-full w-full object-cover object-center" /></div></section><section className="border-t border-border bg-secondary px-5 py-16 text-center"><Instagram className="mx-auto text-accent" size={28} strokeWidth={1.4} /><h2 className="mt-5 font-display text-4xl">Follow the sparkle.</h2><p className="mt-3 text-sm text-muted-foreground">See more from Shivani Jewellers on Instagram.</p><Button variant="textAction" asChild className="mt-7"><a href={INSTAGRAM} target="_blank" rel="noopener noreferrer">Visit Instagram <ArrowUpRight size={16} /></a></Button></section></main>; }